stages:
  - compile
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

image: docker:latest
services:
  - docker:dind

# security testing: https://docs.gitlab.com/ee/user/application_security/
# According to gitlab doc, this is the way to go.. so let's do this!
include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

cache:
  key: "$CI_COMMIT_REF_NAME"
  policy: push
  paths:
    - build
    - .gradle

compile:
  image: gradle:8.11.0-jdk21
  stage: compile
  script:
    - gradle compileJava

test:
  image: gradle:8.11.0-jdk21
  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit: ./build/test-results/test/**/TEST-*.xml

build:
    image: gradle:8.11.0-jdk21
    stage: build
    script:
        - gradle clean bootBuildImage