### Get access token with admin credentials

POST http://localhost:8181/realms/GamePlatform/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id = backend &
client_secret = hjMbDSS6bsMYLsFiiH6ETl7YWSgi3oyv &
username = admin &
password = password &
grant_type = password &
scope = openid

//saving the access token
> {%
    client.global.set("access_token", response.body.access_token);
%}


### Get achievements

GET http://localhost:8090/api/achievements
Authorization: Bearer {{access_token}}


### Get scoreboard

GET http://localhost:8090/api/game-statistics/a7d9b1bc-b94d-4fa1-a1a0-65d7d4359634
Authorization: Bearer {{access_token}}


### Get admin statistics

GET http://localhost:8090/api/admin/statistics
Authorization: Bearer {{access_token}}


### Update game statistics

POST http://localhost:8090/api/game-statistics/update
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "id": 1,
  "gameId": "14910372-c39d-7de7-b05a-93f8166cf7af",
  "playerIds": ["a7d9b1bc-b94d-4fa1-a1a0-65d7d4359634", "b5c0f1b7-3971-4e66-b5ab-49a0f4a71b4d"],
  "startTime": "2024-11-05T12:00:00",
  "endTime": "2024-11-05T12:30:00",
  "isActive": true,
  "winner": "PLAYER1",
  "score": 10,
  "movesMade": 10
}
