### Get access token with admin credentials

POST http://localhost:8181/realms/GamePlatform/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id = backend &
client_secret = 0Ss74BU8bo5Xcq7p3SfxvYRyNmxtkB3E &
username = admin &
password = password &
grant_type = password &
scope = openid

//saving the access token
> {%
    client.global.set("access_token", response.body.access_token);
%}

### Create a new user in Keycloak (Register User)
POST http://localhost:8181/realms/GamePlatform/users
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "newuser",
  "enabled": true,
  "emailVerified": true,
  "firstName": "New",
  "lastName": "User",
  "email": "newuser@example.com",
  "credentials": [{"type": "password", "value": "password"}]
}

### Add a game
POST http://localhost:8090/api/games/add
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "gameName": "Hello-World",
  "description": "A game to say hello to the world",
  "price": 12.0
}

