### Get access token with admin credentials

POST http://localhost:8181/realms/GamePlatform/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id = backend &
client_secret = gGS9JZkQh2MLPIgcr3LjJdwa3H9g5TR8 &
username = admin &
password = password &
grant_type = password &
scope = openid

//saving the access token
> {%
    client.global.set("access_token", response.body.access_token);
%}

