\server:
  port: ${PORT:8092}
  servlet:
    context-path: /api


spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    defer-datasource-initialization: true

