\server:
  port: ${PORT:8092}
  servlet:
    context-path: /api


spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  datasource:
    url: "jdbc:mysql://localhost:13308"
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword