  services:
    mysql_team3_db:
      image: mysql:9.0.1
      restart: no
      environment:
        MYSQL_DATABASE: 'team3_db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '13308:3306'
      networks:
        - backend
      volumes:
        - ./team3/mysql/data:/var/lib/mysql

    team3_rabbitmq:
      image: rabbitmq:3.13.7-management-alpine
      environment:
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_PASS=mypassword
      ports:
        - "5673:5672" #AMQP
        - "15673:15672" #MGMT
      networks:
        - backend
      volumes:
        - ./team3/rabbitmq/data/:/var/lib/rabbitmq/
        - ./team3/rabbitmq/log/:/var/log/rabbitmq/



    idp_mysql_team3:
      image: mysql:9.0.1
      volumes:
        - ./team3/idp_mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      ports:
        - '3308:3306'
      networks:
        - kc

    idp_keycloak_team3:
      image: quay.io/keycloak/keycloak:25.0.5
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB=mysql
        - KC_DB_URL_HOST=idp_mysql_team3
        - KC_DB_URL_DATABASE=keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=password
      command: start-dev
      ports:
        - "8181:8080"
      depends_on:
        - idp_mysql_team3
      networks:
        - kc


  networks:
    kc:
      name: kc-network-team3
      driver: bridge
    backend:
      name: back-network-team3
      driver: bridge

