server:
  port: ${PORT:8090}
  servlet:
    context-path: /api


spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/GamePlatform/protocol/openid-connect/certs
          issuer-uri: http://localhost:8181/realms/GamePlatform

